In [1]:
import numpy as np

In [2]:
#CREATING 20 ELEMENTS ARRAY
Elements = np.arange(20).reshape(4,5)
print(Elements)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [8]:
Elements.dtype

dtype('int32')

In [9]:
Elements.size

20

In [6]:
Elements.shape

(4, 5)

In [7]:
type(Elements)

numpy.ndarray

In [15]:
#ARRAY CREATION

In [17]:
Array2 = np.array([4,5,9,34])
print(Array2)

[ 4  5  9 34]


In [5]:
Array3 = np.array([(1,4,6,10),(3,16,12,2),(9,7,4,12)])
print(Array3)

[[ 1  4  6 10]
 [ 3 16 12  2]
 [ 9  7  4 12]]


In [11]:
Array4 = np.zeros((5,4))
print(Array4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [18]:
Array1=np.arange(3,30,3).reshape(3,3)
print(Array1)

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


In [26]:
Array=np.arange(0,100,2).reshape(5,10)
print(Array)

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [27]:
#BASIC OPERATION - Addition of Array
Ary1=np.array([2,6,4,8])
Ary2=np.array([3,12,9,15])
result = Ary1+Ary2
print(result)

[ 5 18 13 23]


In [28]:
result2=Ary1*Ary2
print(result2)

[  6  72  36 120]


In [37]:
result3=Ary1-Ary2
print(result3)

[-1 -6 -5 -7]


In [42]:
Arra1 = np.array([(1,4,6,10),(3,16,12,2),(9,7,4,12)])
Arra2 = np.array([(2,4,3,2),(3,6,2,2),(5,7,4,2)])
Addition = Arra1 + Arra2
print(Addition)

[[ 3  8  9 12]
 [ 6 22 14  4]
 [14 14  8 14]]


In [34]:
multiply = Arra1 * Arra2
print(multiply)

[[ 2 16 18 20]
 [ 9 96 24  4]
 [45 49 16 24]]


In [41]:
Arra1 = np.array([(1,4,6,10),(3,16,12,2),(9,7,4,12)])
Arra2 = np.array([(2,4,3,2),(3,6,2,2),(5,7,4,2)])
crossmultiply = Arra1@Arra2
print(crossmultiply)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)